#!/usr/local/bin/perl
#
# quick script for sending SNPP messages
#
# $Id$
#
# Copyright (C) 2000 Cornelius Cook
# cook@cpoint.net, http://collective.cpoint.net/
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# http://www.gnu.org/copyleft/gpl.html

use Getopt::Std;
use Net::SNPP;
use Sys::Hostname;

my %opts;
my $VERSION="0.1";

sub Usage {
        die "Usage: $0 [OPTIONS] pin1 [pin2 [...]]

version $VERSION

-h                you're reading it.  :)
-s SERVER[:PORT]  SNPP server to use (default is 'localhost')
-f USER           force page to be from user USER (default is current user)
-m MESSAGE	  message to send (reads from stdin by default)
-n                no email carbonig to 'from'
-d                turn debug on

";
}


# get our options
if (!getopts('hdns:f:m:',\%opts) || $opts{h} || !@ARGV) {
        Usage();
}

$opts{s}='localhost' unless ($opts{s});

$snpp = Net::SNPP->new($opts{s}, Debug => $opts{d} );
if (!defined($snpp)) {
	die "Could not connect to SNPP server '$opts{s}'\n";
}

# get the pins
my @pins = @ARGV;

# get the page text
undef $/;
my $text = $opts{m} ? $opts{m} : <STDIN>;
$/="\n";

# who is it from?
if (!defined($opts{f}) && !$opts{n}) {
	$opts{f}=scalar(getpwuid($<))."\@";
	$opts{f}.=hostname;
}

# send pins
foreach $pin (@pins) {
	if (!$snpp->pager_id($pin)) {
		warn $snpp->message();
		if ($snpp->status()==4) {
			exit($snpp->code()-400);
		}
	}
}

# send 'caller id', if we need to
if (!$opts{n}) {
	if (!$snpp->caller_id($opts{f})) {
		warn $snpp->message();
		if ($snpp->status()==4) {
			exit($snpp->code()-400);
		}
	}
}

# send text
if (!$snpp->data($text)) {
	warn $snpp->message();
	if ($snpp->status()==4) {
		exit($snpp->code()-400);
	}
}

# issue the send
if (!$snpp->send()) {
	warn $snpp->message();
	exit($snpp->code()%100);
}

$snpp->quit;

undef $snpp;
