#!/usr/bin/perl
#
# quick script for testing SNPP messaging
#
# $Id$
#
# Copyright (C) 2000-2004 Kees Cook
# kees@outflux.net, http://outflux.net/
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# http://www.gnu.org/copyleft/gpl.html

use Net::SNPP;

$snpp = Net::SNPP->new('localhost', 
				Port => 2424,
				Debug => 1 );
if (!defined($snpp)) {
	die "Could not connect to SNPP server\n";
}

my ($PIN, $Message) = @ARGV;

if ($snpp->pager_id($PIN)) {
	if ($snpp->content($Message)) {
		$snpp->send();
	}
	else {
		warn $snpp->message();
	}
}
else {
	warn $snpp->message();
}

$snpp->quit;

undef $snpp;
