#!/bin/bash
VERSION=$1

if [ "x$VERSION" = "x" ]; then
	echo 'what version?'
	exit 1
fi

DIR="sendpage-$VERSION"

perl Makefile.PL
make dist
make distclean

mv sendpage-$VERSION.tar.gz ../../tgzs/
(cd ../../rel; tar zxf ../tgzs/sendpage-$VERSION.tar.gz)
