#!/bin/bash
set -e
VERSION=$1

if [ "x$VERSION" = "x" ]; then
	echo 'what version?'
	exit 1
fi

WEB="/kees/projects/web/dist/sendpage.org/"
DIR="sendpage-$VERSION"

perl Makefile.PL
make test
make dist
make distclean

#ncftpput upload.sf.net /incoming sendpage-$VERSION.tar.gz
cp sendpage-$VERSION.tar.gz $WEB/download
rm $WEB/download/LATEST*
touch $WEB/download/LATEST-IS-$VERSION
(cd $WEB/rel; \
        tar zxf ../download/sendpage-$VERSION.tar.gz)
(cd $WEB; \
        for i in Changes THANKS TODO FEATURES LICENSE README sendpage.cf ; do\
                cat rel/sendpage-$VERSION/$i > $i.txt;        \
        done)
#mv sendpage-$VERSION.tar.gz ../../tgzs/
#(cd ../../rel; tar zxf ../tgzs/sendpage-$VERSION.tar.gz)
echo "Edit sendpage.org/content/downloads.inc"
echo "Upload to SourceForge"
